wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1699322930.076578
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.15.12
      8:
      - 2
      - 5
      13: darwin-x86_64
