name: ghapi
on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: insntall dependencies
        run: pip install ghapi

      - name: Make a commet
        run: python .github/scripts/comment.py

        env:
          NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
