on: issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pr_commented:
    if: ${{ contains(github.event.comment.body, '/bug') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: insntall dependencies
        run: pip install ghapi

      - name: Make a commet
        run: python .github/scripts/add_label.py

        env:
          NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
    
