on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python
        env: # load secret as environment variable
          MY_VAR: ${{ secrets.MY_SECRET }}

