name: trigger-demo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # can run workflow manualy

jobs:
  trigger-demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
